name: Check
on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Налаштування PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          # Важливо для Yii2 мати розширення, які вимагає фреймворк
          extensions: mbstring, intl, pdo, pdo_mysql 
          tools: cs2pr, phpcs, composer:v2

      # 2. Встановлення залежностей (Критично для Yii2)
      # Без цього може не працювати валідація, якщо у вас є кастомні правила в vendor
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # 3. Перевірка синтаксису (Lint)
      # Ми явно вказуємо папки Yii2, щоб не сканувати vendor/ або vagrant/
      - name: PHP Syntax Check
        run: find backend common console frontend -name "*.php" -print0 | xargs -0 -n 1 -P 4 php -l

      # 4. Перевірка стандартів коду (Code Sniffer)
      # Вказуємо ті самі папки. 
      # Якщо у вас є файл конфігу phpcs.xml в корені, приберіть прапорець --standard=PSR12
      - name: PHP Code Sniffer
        run: phpcs -q --report=checkstyle --standard=PSR12 backend common console frontend | cs2pr
