name: Check
on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Встановлюємо PHP та інструменти
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: cs2pr, phpcs

      # 2. Явна перевірка синтаксису (Lint)
      - name: PHP Syntax Check
        run: find ./src -name "*.php" -print0 | xargs -0 -n 1 -P 4 php -l

      # 3. Явна перевірка стандартів (Code Sniffer)
      # Тут ми ПРЯМО кажемо: "перевір папку src/"
      - name: PHP Code Sniffer
        run: phpcs -q --report=checkstyle src/ | cs2pr
